version: '3'
services:
  nest:
    build: .
    container_name: nest
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - 9000:9000

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-Nginx
  #   container_name: nest-nginx
  #   depends_on:
  #     - nest
  #   environment:
  #     - NGINX_SERVER_NAME=localhost
  #     - NEST_HOST=nest
  #     - NEST_PORT=9001
  #     - NGINX_MAX_BODY=100M
  #   ports:
  #     - 80:80

  db:
    image: mysql:5.7
    container_name: nest-db
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - mysql57dbdata:/var/lib/mysql

volumes:
  mysql57dbdata:
